// Seed data for Scene Co. Influencer CRM

// Precomputed SHA-256 hash of "password123" for edge-compatible user login
export const MOCK_PASSWORD_HASH = "ef92b778bafe771e8929ab57e5377873737ec59ff6d8d5fb9f668c7e2b347632";

export const SEED_USERS = [
  {
    id: "usr_5",
    name: "Thejaswin P S",
    email: "thejaswinps@gmail.com",
    password_hash: MOCK_PASSWORD_HASH,
    role: "super_admin"
  },
  {
    id: "usr_1",
    name: "Sarah Jenkins",
    email: "superadmin@thescene.co",
    password_hash: MOCK_PASSWORD_HASH,
    role: "super_admin"
  },
  {
    id: "usr_2",
    name: "Alex Rivera",
    email: "admin@thescene.co",
    password_hash: MOCK_PASSWORD_HASH,
    role: "admin"
  },
  {
    id: "usr_3",
    name: "Emily Chen",
    email: "manager@thescene.co",
    password_hash: MOCK_PASSWORD_HASH,
    role: "manager"
  },
  {
    id: "usr_4",
    name: "Marcus Vance",
    email: "viewer@thescene.co",
    password_hash: MOCK_PASSWORD_HASH,
    role: "viewer"
  }
];

export const SEED_BRANDS = [
  {
    id: "brd_1",
    name: "Nike",
    company_name: "Nike India Pvt Ltd",
    industry: "Sports & Apparel",
    contact_person: "Rohit Sharma",
    designation: "Marketing Director",
    email: "rohit.sharma@nike.com",
    phone: "+91 98765 43210",
    website: "https://nike.com",
    budget_range: "₹1,000,000 - ₹5,000,000",
    address: "Prestige Lexicon, Bangalore, Karnataka",
    notes: "Focused on running and fitness influencers. Prefers Reels and YouTube integrations."
  },
  {
    id: "brd_2",
    name: "OnePlus",
    company_name: "OnePlus Technology Co. Ltd",
    industry: "Tech & Electronics",
    contact_person: "Vikas Agarwal",
    designation: "PR Lead",
    email: "vikas@oneplus.com",
    phone: "+91 98123 45678",
    website: "https://oneplus.in",
    budget_range: "₹2,000,000 - ₹10,000,000",
    address: "UB City, Bangalore, Karnataka",
    notes: "Launches new flagship phones twice a year. High standard of video quality required."
  },
  {
    id: "brd_3",
    name: "Zara",
    company_name: "Inditex Trent Retail India",
    industry: "Fashion & Retail",
    contact_person: "Ananya Roy",
    designation: "Brand Manager",
    email: "ananya.roy@zara.com",
    phone: "+91 99887 76655",
    website: "https://zara.com",
    budget_range: "₹500,000 - ₹2,000,000",
    address: "Phoenix Marketcity, Mumbai, Maharashtra",
    notes: "Mainly collaborates on aesthetic Instagram Carousels and Outfit-of-the-Day (OOTD) Reels."
  },
  {
    id: "brd_4",
    name: "Whole Foods Co",
    company_name: "Whole Foods Organic India",
    industry: "Food & Beverage",
    contact_person: "Suresh Menon",
    designation: "Campaign Lead",
    email: "suresh@wholefoods.in",
    phone: "+91 91234 56789",
    website: "https://wholefoodsco.in",
    budget_range: "₹100,000 - ₹500,000",
    address: "Indiranagar, Bangalore, Karnataka",
    notes: "Focuses on organic products, vegan recipes, and clean eating creators. Accepts barter for nano/micro creators."
  },
  {
    id: "brd_5",
    name: "L'Oreal",
    company_name: "L'Oreal India Ltd",
    industry: "Beauty & Cosmetics",
    contact_person: "Priya Tandon",
    designation: "Influencer Marketing Specialist",
    email: "priya.tandon@loreal.com",
    phone: "+91 90000 11111",
    website: "https://loreal.co.in",
    budget_range: "₹1,500,000 - ₹6,000,000",
    address: "Bandra Kurla Complex, Mumbai, Maharashtra",
    notes: "Requires makeup tutorials, product reviews, and lifestyle vlogs. Strong emphasis on skin demographics."
  }
];

export const SEED_INFLUENCERS_RAW = [
  {
    id: "inf_1",
    full_name: "Rohan Kulkarni",
    username: "rohan_travels",
    email: "rohan@gmail.com",
    phone: "+91 98801 12233",
    dob: "1995-04-12",
    gender: "Male",
    bio: "Exploring hidden gems across India. Visual storyteller and photographer.",
    website: "https://rohantravels.com",
    profile_photo: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&h=150&q=80",
    instagram_handle: "rohan_travels",
    instagram_url: "https://instagram.com/rohan_travels",
    youtube_handle: "RohanTravelsVlogs",
    youtube_url: "https://youtube.com/c/RohanTravelsVlogs",
    linkedin_handle: "rohan-kulkarni",
    linkedin_url: "https://linkedin.com/in/rohan-kulkarni",
    facebook_handle: "",
    facebook_url: "",
    twitter_handle: "rohan_travels",
    twitter_url: "https://x.com/rohan_travels",
    snapchat: "rohan_snap",
    moj: "",
    josh: "",
    sharechat: "",
    followers: 125000,
    avg_reach: 45000,
    avg_reel_reach: 80000,
    avg_story_reach: 15000,
    avg_post_reach: 30000,
    avg_views: 65000,
    avg_likes: 8500,
    avg_comments: 420,
    avg_shares: 1200,
    avg_saves: 850,
    engagement_rate: 6.8,
    male_audience_pct: 55,
    female_audience_pct: 45,
    age_13_17_pct: 10,
    age_18_24_pct: 45,
    age_25_34_pct: 35,
    age_35_44_pct: 8,
    age_45_plus_pct: 2,
    top_cities: JSON.stringify(["Bangalore", "Mumbai", "Pune"]),
    top_states: JSON.stringify(["Karnataka", "Maharashtra", "Delhi"]),
    top_countries: JSON.stringify(["India", "United Arab Emirates"]),
    country: "India",
    state: "Karnataka",
    city: "Bangalore",
    area: "Indiranagar",
    pincode: "560038",
    primary_lang: "Kannada",
    secondary_langs: JSON.stringify(["English", "Hindi"]),
    story_price: 12000,
    static_post_price: 20000,
    carousel_price: 25000,
    reel_price: 35000,
    youtube_integration_price: 60000,
    event_appearance_price: 45000,
    ugc_video_price: 20000,
    collab_preferences: JSON.stringify(["Paid Promotion", "Brand Ambassador", "Event Appearance"]),
    availability_status: "Available",
    content_quality_rating: 9,
    communication_rating: 8,
    professionalism_rating: 9,
    reliability_rating: 9,
    brand_fit_rating: 8,
    notes: "Very professional, delivers content on time. Excellent color grading on videos.",
    strengths: "Drone shots, cinematic editing, engaging travel itineraries.",
    weaknesses: "Slightly high rates for smaller campaigns.",
    preferred_brands: "Gopro, Decathlon, Nike",
    brands_avoided: "Fast fashion brands, cheap electronics",
    categories: ["Travel", "Photography", "UGC Creator"],
    languages: ["Kannada", "English", "Hindi"]
  },
  {
    id: "inf_2",
    full_name: "Priya Sharma",
    username: "priya_fit_life",
    email: "priya.fit@gmail.com",
    phone: "+91 99000 88888",
    dob: "1998-08-25",
    gender: "Female",
    bio: "Certified nutritionist. Helping you build a sustainable healthy lifestyle.",
    website: "",
    profile_photo: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=150&h=150&q=80",
    instagram_handle: "priya_fit_life",
    instagram_url: "https://instagram.com/priya_fit_life",
    youtube_handle: "PriyaFitLife",
    youtube_url: "https://youtube.com/c/PriyaFitLife",
    linkedin_handle: "",
    linkedin_url: "",
    facebook_handle: "",
    facebook_url: "",
    twitter_handle: "",
    twitter_url: "",
    snapchat: "",
    moj: "priyamoj",
    josh: "",
    sharechat: "",
    followers: 45000,
    avg_reach: 18000,
    avg_reel_reach: 32000,
    avg_story_reach: 8000,
    avg_post_reach: 12000,
    avg_views: 25000,
    avg_likes: 2200,
    avg_comments: 150,
    avg_shares: 800,
    avg_saves: 950,
    engagement_rate: 5.2,
    male_audience_pct: 30,
    female_audience_pct: 70,
    age_13_17_pct: 15,
    age_18_24_pct: 50,
    age_25_34_pct: 25,
    age_35_44_pct: 8,
    age_45_plus_pct: 2,
    top_cities: JSON.stringify(["Mumbai", "Bangalore", "Delhi"]),
    top_states: JSON.stringify(["Maharashtra", "Karnataka", "Delhi"]),
    top_countries: JSON.stringify(["India"]),
    country: "India",
    state: "Maharashtra",
    city: "Mumbai",
    area: "Bandra West",
    pincode: "400050",
    primary_lang: "Hindi",
    secondary_langs: JSON.stringify(["English"]),
    story_price: 6000,
    static_post_price: 10000,
    carousel_price: 12000,
    reel_price: 18000,
    youtube_integration_price: 35000,
    event_appearance_price: 25000,
    ugc_video_price: 12000,
    collab_preferences: JSON.stringify(["Paid Promotion", "Barter Collaboration", "Product Review"]),
    availability_status: "Available",
    content_quality_rating: 8,
    communication_rating: 9,
    professionalism_rating: 8,
    reliability_rating: 8,
    brand_fit_rating: 9,
    notes: "Great engagement on diet charts. Friendly and responds very fast.",
    strengths: "Recipe reels, detailed supplement reviews, workout tips.",
    weaknesses: "Requires full creative control over captions.",
    preferred_brands: "Myprotein, Whole Foods Co, Cult.fit",
    brands_avoided: "Junk food brands, weight loss teas",
    categories: ["Fitness", "Health", "Food"],
    languages: ["Hindi", "English"]
  },
  {
    id: "inf_3",
    full_name: "Kabir Mehta",
    username: "kabir_techs",
    email: "kabir@mehtatech.com",
    phone: "+91 97766 55443",
    dob: "1993-11-02",
    gender: "Male",
    bio: "Unboxing tomorrow's tech today. Detailed reviews & setup inspiration.",
    website: "https://mehtatech.com",
    profile_photo: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&h=150&q=80",
    instagram_handle: "kabir_techs",
    instagram_url: "https://instagram.com/kabir_techs",
    youtube_handle: "KabirTechReviews",
    youtube_url: "https://youtube.com/c/KabirTechReviews",
    linkedin_handle: "kabirmehta",
    linkedin_url: "https://linkedin.com/in/kabirmehta",
    facebook_handle: "",
    facebook_url: "",
    twitter_handle: "kabir_techs",
    twitter_url: "https://x.com/kabir_techs",
    snapchat: "",
    moj: "",
    josh: "",
    sharechat: "",
    followers: 680000,
    avg_reach: 220000,
    avg_reel_reach: 410000,
    avg_story_reach: 45000,
    avg_post_reach: 180000,
    avg_views: 350000,
    avg_likes: 38000,
    avg_comments: 2900,
    avg_shares: 4500,
    avg_saves: 3800,
    engagement_rate: 6.0,
    male_audience_pct: 88,
    female_audience_pct: 12,
    age_13_17_pct: 18,
    age_18_24_pct: 48,
    age_25_34_pct: 26,
    age_35_44_pct: 6,
    age_45_plus_pct: 2,
    top_cities: JSON.stringify(["Delhi", "Bangalore", "Mumbai"]),
    top_states: JSON.stringify(["Delhi", "Karnataka", "Maharashtra"]),
    top_countries: JSON.stringify(["India", "United States", "Singapore"]),
    country: "India",
    state: "Delhi",
    city: "Delhi",
    area: "Connaught Place",
    pincode: "110001",
    primary_lang: "English",
    secondary_langs: JSON.stringify(["Hindi"]),
    story_price: 35000,
    static_post_price: 60000,
    carousel_price: 75000,
    reel_price: 95000,
    youtube_integration_price: 180000,
    event_appearance_price: 100000,
    ugc_video_price: 50000,
    collab_preferences: JSON.stringify(["Paid Promotion", "Brand Ambassador", "Product Review"]),
    availability_status: "Busy",
    content_quality_rating: 10,
    communication_rating: 7,
    professionalism_rating: 10,
    reliability_rating: 9,
    brand_fit_rating: 9,
    notes: "Top-tier videography. Studio setup is state-of-the-art. Highly sought after for phone launches.",
    strengths: "Ultra-high quality video, detailed specifications breakdown, loyal subscriber base.",
    weaknesses: "Rigid timeline, strictly non-negotiable rates.",
    preferred_brands: "Apple, OnePlus, Samsung, Asus",
    brands_avoided: "Low-end generic accessories",
    categories: ["Tech", "Gaming", "Lifestyle"],
    languages: ["English", "Hindi"]
  },
  {
    id: "inf_4",
    full_name: "Sneha Sen",
    username: "snehasen_beauty",
    email: "snehasen@gmail.com",
    phone: "+91 96111 22233",
    dob: "1997-02-15",
    gender: "Female",
    bio: "Skincare enthusiast & bridal makeup artist. Glow from within.",
    website: "",
    profile_photo: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&h=150&q=80",
    instagram_handle: "snehasen_beauty",
    instagram_url: "https://instagram.com/snehasen_beauty",
    youtube_handle: "",
    youtube_url: "",
    linkedin_handle: "",
    linkedin_url: "",
    facebook_handle: "",
    facebook_url: "",
    twitter_handle: "",
    twitter_url: "",
    snapchat: "",
    moj: "",
    josh: "",
    sharechat: "",
    followers: 82000,
    avg_reach: 29000,
    avg_reel_reach: 55000,
    avg_story_reach: 12000,
    avg_post_reach: 22000,
    avg_views: 48000,
    avg_likes: 4100,
    avg_comments: 320,
    avg_shares: 980,
    avg_saves: 1450,
    engagement_rate: 5.4,
    male_audience_pct: 8,
    female_audience_pct: 92,
    age_13_17_pct: 12,
    age_18_24_pct: 44,
    age_25_34_pct: 32,
    age_35_44_pct: 10,
    age_45_plus_pct: 2,
    top_cities: JSON.stringify(["Kolkata", "Mumbai", "Delhi"]),
    top_states: JSON.stringify(["West Bengal", "Maharashtra", "Delhi"]),
    top_countries: JSON.stringify(["India"]),
    country: "India",
    state: "West Bengal",
    city: "Kolkata",
    area: "Salt Lake",
    pincode: "700091",
    primary_lang: "Bengali",
    secondary_langs: JSON.stringify(["English", "Hindi"]),
    story_price: 8000,
    static_post_price: 15000,
    carousel_price: 18000,
    reel_price: 25000,
    youtube_integration_price: 0,
    event_appearance_price: 35000,
    ugc_video_price: 15000,
    collab_preferences: JSON.stringify(["Paid Promotion", "Barter Collaboration", "UGC Creation"]),
    availability_status: "Available",
    content_quality_rating: 8,
    communication_rating: 8,
    professionalism_rating: 8,
    reliability_rating: 7,
    brand_fit_rating: 8,
    notes: "High save rate on makeup tutorials. Very relatable tone.",
    strengths: "Detailed skincare routines, honest beauty product reviews.",
    weaknesses: "Sometimes requires reminders to send draft links.",
    preferred_brands: "L'Oreal, Mac Cosmetics, Nykaa",
    brands_avoided: "Unregulated skin-lightening creams",
    categories: ["Beauty", "Luxury", "UGC Creator"],
    languages: ["Bengali", "English", "Hindi"]
  },
  {
    id: "inf_5",
    full_name: "Vikram Malhotra",
    username: "vikram_wheels",
    email: "vikram@wheelsmedia.in",
    phone: "+91 95555 44444",
    dob: "1991-09-22",
    gender: "Male",
    bio: "Supercars, bikes, and open roads. Automotive editor and reviewer.",
    website: "https://wheelsmedia.in",
    profile_photo: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=150&h=150&q=80",
    instagram_handle: "vikram_wheels",
    instagram_url: "https://instagram.com/vikram_wheels",
    youtube_handle: "VikramWheelsTV",
    youtube_url: "https://youtube.com/c/VikramWheelsTV",
    linkedin_handle: "vikram-malhotra-wheels",
    linkedin_url: "https://linkedin.com/in/vikram-malhotra-wheels",
    facebook_handle: "",
    facebook_url: "",
    twitter_handle: "vikram_wheels",
    twitter_url: "https://x.com/vikram_wheels",
    snapchat: "",
    moj: "",
    josh: "",
    sharechat: "",
    followers: 1200000,
    avg_reach: 420000,
    avg_reel_reach: 890000,
    avg_story_reach: 85000,
    avg_post_reach: 350000,
    avg_views: 950000,
    avg_likes: 92000,
    avg_comments: 5400,
    avg_shares: 15000,
    avg_saves: 8200,
    engagement_rate: 8.1,
    male_audience_pct: 94,
    female_audience_pct: 6,
    age_13_17_pct: 20,
    age_18_24_pct: 50,
    age_25_34_pct: 22,
    age_35_44_pct: 6,
    age_45_plus_pct: 2,
    top_cities: JSON.stringify(["Mumbai", "Delhi", "Pune"]),
    top_states: JSON.stringify(["Maharashtra", "Delhi", "Karnataka"]),
    top_countries: JSON.stringify(["India", "Germany", "United Kingdom"]),
    country: "India",
    state: "Maharashtra",
    city: "Mumbai",
    area: "Juhu",
    pincode: "400049",
    primary_lang: "English",
    secondary_langs: JSON.stringify(["Hindi"]),
    story_price: 60000,
    static_post_price: 110000,
    carousel_price: 130000,
    reel_price: 180000,
    youtube_integration_price: 300000,
    event_appearance_price: 200000,
    ugc_video_price: 90000,
    collab_preferences: JSON.stringify(["Paid Promotion", "Brand Ambassador"]),
    availability_status: "Booked",
    content_quality_rating: 10,
    communication_rating: 9,
    professionalism_rating: 9,
    reliability_rating: 10,
    brand_fit_rating: 8,
    notes: "Mega creator. Exceptional production quality (uses professional camera crews). High conversion rates for automobile brands.",
    strengths: "Thorough testing, track day reviews, high speed action shots.",
    weaknesses: "Very expensive. Booked out 2 months in advance.",
    preferred_brands: "BMW, Audi, Mercedes, OnePlus",
    brands_avoided: "Local motor parts, suspicious performance boosters",
    categories: ["Automobile", "Luxury", "Business"],
    languages: ["English", "Hindi"]
  },
  {
    id: "inf_6",
    full_name: "Amit Gowda",
    username: "amit_gowda_cooking",
    email: "amit.gowda@gmail.com",
    phone: "+91 94812 34567",
    dob: "1994-06-30",
    gender: "Male",
    bio: "Sharing traditional Karnataka recipes and Bangalore food guides. 100% vegetarian.",
    website: "",
    profile_photo: "https://images.unsplash.com/photo-1542909168-82c3e7fdca5c?auto=format&fit=crop&w=150&h=150&q=80",
    instagram_handle: "amit_gowda_cooking",
    instagram_url: "https://instagram.com/amit_gowda_cooking",
    youtube_handle: "AmitGowdaVegRecipes",
    youtube_url: "https://youtube.com/c/AmitGowdaVegRecipes",
    linkedin_handle: "",
    linkedin_url: "",
    facebook_handle: "",
    facebook_url: "",
    twitter_handle: "",
    twitter_url: "",
    snapchat: "",
    moj: "",
    josh: "",
    sharechat: "",
    followers: 62000,
    avg_reach: 24000,
    avg_reel_reach: 48000,
    avg_story_reach: 8500,
    avg_post_reach: 18000,
    avg_views: 38000,
    avg_likes: 3600,
    avg_comments: 240,
    avg_shares: 1600,
    avg_saves: 1100,
    engagement_rate: 6.2,
    male_audience_pct: 42,
    female_audience_pct: 58,
    age_13_17_pct: 8,
    age_18_24_pct: 35,
    age_25_34_pct: 42,
    age_35_44_pct: 12,
    age_45_plus_pct: 3,
    top_cities: JSON.stringify(["Bangalore", "Mysore", "Hubli"]),
    top_states: JSON.stringify(["Karnataka"]),
    top_countries: JSON.stringify(["India"]),
    country: "India",
    state: "Karnataka",
    city: "Bangalore",
    area: "Malleshwaram",
    pincode: "560003",
    primary_lang: "Kannada",
    secondary_langs: JSON.stringify(["English"]),
    story_price: 5000,
    static_post_price: 8000,
    carousel_price: 10000,
    reel_price: 15000,
    youtube_integration_price: 28000,
    event_appearance_price: 15000,
    ugc_video_price: 8000,
    collab_preferences: JSON.stringify(["Paid Promotion", "Barter Collaboration", "Local Creator"]),
    availability_status: "Available",
    content_quality_rating: 8,
    communication_rating: 9,
    professionalism_rating: 8,
    reliability_rating: 9,
    brand_fit_rating: 9,
    notes: "Strong hyper-local presence in Bangalore. Excellent results for regional food and retail brands.",
    strengths: "Fluent Kannada presentation, authentic traditional recipes, high-quality audio.",
    weaknesses: "Mainly limited to regional/Karnataka audience.",
    preferred_brands: "MTR, Whole Foods Co, local eateries",
    brands_avoided: "Non-vegetarian brands, alcoholic beverages",
    categories: ["Food", "Lifestyle", "Local Creator"],
    languages: ["Kannada", "English"]
  }
];

// Calculation utility for database scores & grade
export function calculateInfluencerScores(inf: any) {
  const followers = inf.followers || 1000;
  const er = inf.engagement_rate || 1.0;
  
  const contentRating = inf.content_quality_rating || 5;
  const commRating = inf.communication_rating || 5;
  const profRating = inf.professionalism_rating || 5;
  const relRating = inf.reliability_rating || 5;
  const brandFit = inf.brand_fit_rating || 5;

  // 1. Reach Score (Logarithmic, 10 to 100)
  // 1k -> ~46, 10k -> ~61, 100k -> ~76, 1M -> ~92, 10M -> 100
  const reachScore = Math.max(10, Math.min(100, Math.round(100 * (Math.log10(followers) / 6.5))));

  // 2. Engagement Score (Base on ER. ER of 6.5% -> 100)
  const engagementScore = Math.max(10, Math.min(100, Math.round(er * 15)));

  // 3. Content Quality Score
  const contentQualityScore = contentRating * 10;

  // 4. Communication Score
  const communicationScore = commRating * 10;

  // 5. Campaign Performance Score
  const campaignPerformanceScore = Math.round(((profRating + relRating + brandFit) / 3) * 10);

  // 6. Overall Score (Average)
  const overallScore = Math.round(
    (reachScore + engagementScore + contentQualityScore + communicationScore + campaignPerformanceScore) / 5
  );

  // 7. Overall Grade
  let overallGrade = "C";
  if (overallScore >= 90) overallGrade = "A+";
  else if (overallScore >= 80) overallGrade = "A";
  else if (overallScore >= 65) overallGrade = "B";
  else if (overallScore >= 45) overallGrade = "C";
  else overallGrade = "D";

  return {
    ...inf,
    reach_score: reachScore,
    engagement_score: engagementScore,
    content_quality_score: contentQualityScore,
    communication_score: communicationScore,
    campaign_performance_score: campaignPerformanceScore,
    overall_score: overallScore,
    overall_grade: overallGrade
  };
}

export const SEED_INFLUENCERS = SEED_INFLUENCERS_RAW.map(calculateInfluencerScores);

export const SEED_CAMPAIGNS = [
  {
    id: "cmp_1",
    name: "OnePlus 12 Launch Campaign",
    brand_id: "brd_2",
    type: "Unboxing & Review",
    budget: 500000,
    start_date: "2026-07-01",
    end_date: "2026-07-30",
    deliverables: "1 YouTube Integration (10+ min), 1 Instagram Reel (OOTD format or tech transition), 1 Story set.",
    objectives: "Drive pre-orders for the OnePlus 12. Highlight the 100W fast charging and Hasselblad camera system.",
    stage: "Planning"
  },
  {
    id: "cmp_2",
    name: "Zara Summer Trends 2026",
    brand_id: "brd_3",
    type: "Fashion Haul",
    budget: 150000,
    start_date: "2026-06-10",
    end_date: "2026-06-25",
    deliverables: "1 Instagram Carousel post, 1 Instagram Reel showing 3 summer outfits, 2 Stories with links.",
    objectives: "Showcase Zara's new linen summer wear. Target young females in metro cities.",
    stage: "Running"
  },
  {
    id: "cmp_3",
    name: "Nike Run Club Promotion",
    brand_id: "brd_1",
    type: "Fitness Challenge",
    budget: 300000,
    start_date: "2026-08-01",
    end_date: "2026-08-31",
    deliverables: "Weekly Reels (4 total) participating in the Nike Run Challenge, 1 Event appearance.",
    objectives: "Increase downloads for the Nike Run Club app in India. Focus on lifestyle running.",
    stage: "Negotiation"
  },
  {
    id: "cmp_4",
    name: "Whole Foods Organic Cooking Vlogs",
    brand_id: "brd_4",
    type: "Barter Recipe Promo",
    budget: 20000,
    start_date: "2026-06-01",
    end_date: "2026-06-20",
    deliverables: "2 Instagram Reels showing organic recipe preparation, tagging Whole Foods. 3 Story frames.",
    objectives: "Highlight the quality of organic cooking ingredients. Drive traffic to the Indiranagar store.",
    stage: "Completed"
  }
];

export const SEED_CAMPAIGN_INFLUENCERS = [
  // OnePlus 12 Launch - Kabir Techs (assigned/negotiating)
  {
    campaign_id: "cmp_1",
    influencer_id: "inf_3",
    status: "Negotiating",
    reach_generated: 0,
    views_generated: 0,
    engagement_generated: 0,
    payment_amount: 180000.0,
    invoice_status: "Pending",
    deliverables_completed: ""
  },
  // OnePlus 12 Launch - Rohan Kulkarni (approved)
  {
    campaign_id: "cmp_1",
    influencer_id: "inf_1",
    status: "Approved",
    reach_generated: 0,
    views_generated: 0,
    engagement_generated: 0,
    payment_amount: 60000.0,
    invoice_status: "Pending",
    deliverables_completed: ""
  },
  // Zara Summer Trends - Priya Sharma (running)
  {
    campaign_id: "cmp_2",
    influencer_id: "inf_2",
    status: "Running",
    reach_generated: 12000,
    views_generated: 18000,
    engagement_generated: 950,
    payment_amount: 18000.0,
    invoice_status: "Invoiced",
    deliverables_completed: "https://instagram.com/p/C_zara_summer_priya"
  },
  // Zara Summer Trends - Sneha Sen (running)
  {
    campaign_id: "cmp_2",
    influencer_id: "inf_4",
    status: "Running",
    reach_generated: 25000,
    views_generated: 38000,
    engagement_generated: 2100,
    payment_amount: 25000.0,
    invoice_status: "Pending",
    deliverables_completed: "https://instagram.com/p/C_zara_style_sneha"
  },
  // Whole Foods Organic Vlogs - Amit Gowda (completed)
  {
    campaign_id: "cmp_4",
    influencer_id: "inf_6",
    status: "Deliverables Completed",
    reach_generated: 45000,
    views_generated: 52000,
    engagement_generated: 3200,
    payment_amount: 15000.0,
    invoice_status: "Paid",
    deliverables_completed: "https://instagram.com/p/C_wf_recipe_amit"
  }
];

export const SEED_PAYMENTS = [
  // Zara Brand payment (brand payment, pending)
  {
    id: "pay_1",
    campaign_id: "cmp_2",
    influencer_id: null,
    brand_id: "brd_3",
    amount: 150000.0,
    type: "brand_payment",
    status: "Pending",
    due_date: "2026-06-30",
    paid_date: null,
    invoice_url: "/invoices/zara_invoice_summer_2026.pdf",
    notes: "Awaiting final deliverables verification before release."
  },
  // Whole Foods Brand payment (brand payment, completed)
  {
    id: "pay_2",
    campaign_id: "cmp_4",
    influencer_id: null,
    brand_id: "brd_4",
    amount: 20000.0,
    type: "brand_payment",
    status: "Completed",
    due_date: "2026-06-15",
    paid_date: "2026-06-14",
    invoice_url: "/invoices/wf_invoice_organic.pdf",
    notes: "Payment cleared via net banking."
  },
  // Whole Foods Payout to Amit Gowda (influencer payout, completed)
  {
    id: "pay_3",
    campaign_id: "cmp_4",
    influencer_id: "inf_6",
    brand_id: null,
    amount: 15000.0,
    type: "influencer_payout",
    status: "Completed",
    due_date: "2026-06-25",
    paid_date: "2026-06-20",
    invoice_url: "/invoices/amit_gowda_payout_wf.pdf",
    notes: "Paid for recipe reels."
  },
  // Zara Payout to Priya Sharma (influencer payout, pending)
  {
    id: "pay_4",
    campaign_id: "cmp_2",
    influencer_id: "inf_2",
    brand_id: null,
    amount: 18000.0,
    type: "influencer_payout",
    status: "Pending",
    due_date: "2026-06-28",
    paid_date: null,
    invoice_url: "/invoices/priya_zara_invoice.pdf",
    notes: "Will release payout immediately after final campaign report approval."
  }
];

export const SEED_ACTIVITIES = [
  {
    id: "act_1",
    influencer_id: "inf_1",
    brand_id: null,
    campaign_id: null,
    type: "whatsapp",
    content: "Sent initial outreach regarding upcoming travel camera campaign. Rohan responded saying he is available in July.",
    created_by: "usr_3",
    created_at: "2026-06-15 10:30:00"
  },
  {
    id: "act_2",
    influencer_id: "inf_3",
    brand_id: null,
    campaign_id: "cmp_1",
    type: "call",
    content: "Briefed Kabir on the OnePlus 12 launch campaign. Discussed pricing; he agreed to do the YouTube integration for 1.8L (down from 2L) if contract signed by June 20.",
    created_by: "usr_3",
    created_at: "2026-06-16 14:15:00"
  },
  {
    id: "act_3",
    influencer_id: null,
    brand_id: "brd_3",
    campaign_id: "cmp_2",
    type: "meeting",
    content: "Met with Zara marketing team to present drafts from Priya and Sneha. They approved both drafts with minor caption tweaks.",
    created_by: "usr_2",
    created_at: "2026-06-17 11:00:00"
  },
  {
    id: "act_4",
    influencer_id: "inf_6",
    brand_id: null,
    campaign_id: "cmp_4",
    type: "follow_up",
    content: "Sent final payment confirmation receipt to Amit Gowda. He confirmed receipt and expressed interest in future barter collaborations.",
    created_by: "usr_3",
    created_at: "2026-06-18 16:45:00"
  }
];

export const SEED_NOTES = [
  {
    id: "nte_1",
    influencer_id: "inf_1",
    brand_id: null,
    content: "Responds best via WhatsApp. Prefers payments via direct bank transfer.",
    created_by: "usr_3"
  },
  {
    id: "nte_2",
    influencer_id: null,
    brand_id: "brd_1",
    content: "Strict requirements regarding trademark and logo usage. Always get legal review on Nike contracts.",
    created_by: "usr_2"
  }
];
